### ISSUE TITLE
Error since async is now a reserved keyword in python 3.7

### ISSUE THREAD

**Issue by txtsd** [mozilla/cipherscan#168]
```
└─▶ ./cipherscan --sigalg mozilla.org                                                                                         
.......................................Traceback (most recent call last):
  File "cscan.py", line 6, in <module>
    from tlslite.messages import ClientHello, ServerHello, ServerHelloDone, Alert
  File "/home/txtsd/git/cipherscan/tlslite/__init__.py", line 27, in <module>
    from tlslite.api import *
  File "/home/txtsd/git/cipherscan/tlslite/api.py", line 11, in <module>
    from .tlsconnection import TLSConnection
  File "/home/txtsd/git/cipherscan/tlslite/tlsconnection.py", line 112
    async=False):
        ^
SyntaxError: invalid syntax
....

```

**Comment by tomato42** [comment]
please use new tlslite-ng, [version 0.7.2](https://github.com/tomato42/tlslite-ng/blob/tlslite-ng-0.7/README.md#12-history) was released specifically to fix this issue

**Comment by txtsd** [comment]
@tomato42 What is the relationship between cipherscan and tlslite-ng?

**Comment by tomato42** [comment]
cipherscan uses tlslite-ng for some of its tests, we want to use the newest tlslite-ng, but we don't want to update it every time cipherscan is executed (as that has non-insignificant impact on the mass-scanning)

**Comment by txtsd** [comment]
Thanks for clearing it up.
